spring:
  application:
    name: mcp-server

  security:
    user:
      name: admin
      password: admin

  datasource:
    url: jdbc:postgresql://localhost:5432/mcp_db
    username: admin
    password: admin
    driver-class-name: org.postgresql.Driver
    hikari:
      minimum-idle: 5
      maximum-pool-size: 10
      idle-timeout: 10000

  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true

  liquibase:
    change-log: classpath:/db/changelog/db.changelog-master.yaml

  ai:
    mcp:
      server:
        enabled: true
        name: stdio-mcp-server
        version: 1.0.0
        type: SYNC